# .github/workflows/test.yml
name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run 3A
        run: cd src/raft && go test -v -race -count 1 -run TestInitialElection3A -timeout 60s ./...
      - name: Run 3B
        run: cd src/raft && go test -v -race -count 1 -run TestBasicAgree3B -timeout 60s ./...
      - name: Run 3C
        run: cd src/raft && go test -v -race -count 1 -run TestPersist13C -timeout 60s ./...
      - name: Run 3D
        run: cd src/raft && go test -v -race -count 1 -run TestSnapshotBasic3D -timeout 120s ./...